.TH "/Users/ahmed/Work/MathFin/base Directory Reference" 3 "Mon Dec 26 2016" "Version 1.0" "MathFin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/ahmed/Work/MathFin/base Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBerror\&.cpp\fP"
.br
.ti -1c
.RI "file \fBerror\&.hpp\fP"
.br
.ti -1c
.RI "file \fBerrorTest\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtypes\&.hpp\fP"
.br
.RI "\fICustom types\&. \fP"
.in -1c
