.TH "FinMath::Error" 3 "Mon Dec 26 2016" "Version 1.0" "MathFin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FinMath::Error \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBError\fP (const std::string &file, long line, const std::string &functionName, const std::string &message='')"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const   throw ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MathFin from the source code\&.
