.TH "MathFin::detail::short_period_holder" 3 "Mon Dec 26 2016" "Version 1.0" "MathFin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MathFin::detail::short_period_holder \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshort_period_holder\fP (\fBPeriod\fP p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPeriod\fP \fBp\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MathFin from the source code\&.
