.TH "/Users/ahmed/Work/MathFin/time/timeunit.hpp" 3 "Mon Dec 26 2016" "Version 1.0" "MathFin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/ahmed/Work/MathFin/time/timeunit.hpp \- TimeUnit enumeration\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iosfwd>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTimeUnit\fP { \fBDays\fP, \fBWeeks\fP, \fBMonths\fP, \fBYears\fP, \fBHours\fP, \fBMinutes\fP, \fBSeconds\fP, \fBMilliseconds\fP, \fBMicroseconds\fP }
.RI "\fIUnits used to describe time periods\&. \fP""
.br
.in -1c
.SH "Detailed Description"
.PP 
TimeUnit enumeration\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for MathFin from the source code\&.
