.TH "/Users/ahmed/Work/MathFin/base/types.hpp" 3 "Mon Dec 26 2016" "Version 1.0" "MathFin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/ahmed/Work/MathFin/base/types.hpp \- Custom types\&.  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBMathFin::Integer\fP"
.br
.RI "\fIinteger number \fP"
.ti -1c
.RI "typedef long \fBMathFin::BigInteger\fP"
.br
.RI "\fIlarge integer number \fP"
.ti -1c
.RI "typedef unsigned int \fBMathFin::Natural\fP"
.br
.RI "\fIpositive number \fP"
.ti -1c
.RI "typedef unsigned long \fBMathFin::BigNatural\fP"
.br
.RI "\fIlarge positive number \fP"
.ti -1c
.RI "typedef double \fBMathFin::Real\fP"
.br
.RI "\fIreal number \fP"
.ti -1c
.RI "typedef Real \fBMathFin::Decimal\fP"
.br
.RI "\fIdecimal number \fP"
.ti -1c
.RI "typedef std::size_t \fBMathFin::Size\fP"
.br
.RI "\fIsize of a container \fP"
.ti -1c
.RI "typedef Real \fBMathFin::Time\fP"
.br
.RI "\fIcontinuous quantity with 1-year units \fP"
.ti -1c
.RI "typedef Real \fBMathFin::DiscountFactor\fP"
.br
.RI "\fIdiscount factor between dates \fP"
.ti -1c
.RI "typedef Real \fBMathFin::Rate\fP"
.br
.RI "\fIinterest rates \fP"
.ti -1c
.RI "typedef Real \fBMathFin::Spread\fP"
.br
.RI "\fIspreads on interest rates \fP"
.ti -1c
.RI "typedef Real \fBMathFin::Volatility\fP"
.br
.RI "\fIvolatility \fP"
.ti -1c
.RI "typedef Real \fBMathFin::Probability\fP"
.br
.RI "\fIprobability \fP"
.in -1c
.SH "Detailed Description"
.PP 
Custom types\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for MathFin from the source code\&.
